version: '3.4'

services:
  helloworldnest:
    image: helloworldnest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
